### ISSUE TITLE
UI build script should cover sequences in the manifest file

### ISSUE THREAD

**Issue by duynguyen** [adobe/adobeio-cna-starter-project#19]
### Expected Behaviour
Action sequence should be covered by the UI build script so that it can be called from the UI.

### Actual Behaviour
Sequences can not be called from the UI.

### Reproduce Scenario (including but not limited to)
Applications that need to invoke a sequence of actions instead of single actions.

#### Steps to Reproduce
In manifest.yml, add `sequences` section:
```
packages:
  __CNA_PACKAGE__:
    license: Apache-2.0
    actions:
      hello:
        function: actions/hello/index.js
        web: yes
        runtime: 'nodejs:10'
      hello2:
        function: actions/hello/index.js
        web: yes
        runtime: 'nodejs:10'
    sequences:
      hello-sequence:
        actions: hello, hello2
```

#### Sample Code that illustrates the problem
Please see `Steps to reproduce`.
