### ISSUE TITLE
When using the ZIP action the JavaScript won't be build

### ISSUE THREAD

**Issue by maximilianvoss** [adobe/adobeio-cna-starter-project#22]
- Take the hello action from the CNA starter
- Change the manifest.yaml in following way so the ZIP build is executed from scripts/build.action.js

```
packages:
  __CNA_PACKAGE__:
    license: Apache-2.0
    actions:
      hello:
        function: actions/hello
        web: yes
        runtime: 'nodejs:10'
```

A ZIP is build, but the JavaScript is never compiled with npm.

**Comment by moritzraho** [comment]
@maximilianvoss you need to add a `package.json` file into the `actions/hello` folder if you want to package your actions as a zip action.
Are there any reasons you want to use a zip action? It is usually more efficient to use the bundled action (point to a file)

**Comment by duynguyen** [comment]
+1
We should discourage the use of zip action, as it has major impact on action execution time (especially cold start).

**Comment by maximilianvoss** [comment]
Just imagine you want to create an action which authenticates against Adobe IO, where would you put the private key?

**Comment by maximilianvoss** [comment]
nevertheless, the package.json did the trick. Closing.
Thanks a lot

**Comment by moritzraho** [comment]
The common way of doing this would be to define a default parameter for your action in your `manifest.yml`, like 
```
packages:
  __CNA_PACKAGE__:
    license: Apache-2.0
    actions:
      hello:
        function: actions/hello/index.js
        web: yes
        runtime: 'nodejs:10'
        input:
          key: ${KEY_VALUE}
```
And then you save the KEY_VALUE in your `.env` so that your key is not visible in your repository
You can then get the `key` from your main function args in the action
